//
//  UserDataProvider.swift
//  FakeNFT
//
//  Created by Александр Пичугин on 08.10.2023.
//

import Foundation

protocol UserDataProvider {
    func getActualUserData(completion: @escaping([UserModel]) -> Void)
}

final class StatisticDataProvider: UserDataProvider {
    
    func getActualUserData(completion: @escaping([UserModel]) -> Void) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            completion(UserModel.mockUserData)
        }
    }
    
}

private extension UserModel {
    static var mockUserData: [UserModel] {
        [UserModel(name: "Alex",
                   avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                   description: "Очень хороший друг",
                   website: "https://ya.ru",
                   nfts: [NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "1",
                                                     id: "757"),
                                   id: "6786"),
                          NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "2",
                                                     id: "757"),
                                   id: "6786"),
                          NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "3",
                                                     id: "757"),
                                   id: "6786")
                   ],
                   rating: "13",
                   id: "1"),

         UserModel(name: "Bolex",
                   avatar: "https://img.goodfon.ru/original/800x480/4/cf/chiornaia-zmeia-red-belly-black-iazyk.jpg",
                   description: "Очень плохое существо",
                   website: "https://ya.ru",
                   nfts: [],
                   rating: "4",
                   id: "2"),

         UserModel(name: "",
                   avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                   description: "Странный",
                   website: "https://ya.ru",
                   nfts: [],
                   rating: "5",
                   id: "4"),

         UserModel(name: "Slon",
                   avatar: "https://i.ytimg.com/vi/p2jXct3Ewbo/hqdefault.jpg",
                   description: "Очень дерзкий",
                   website: "https://ya.ru",
                   nfts: [],
                   rating: "Битый рейтинг",
                   id: "6"),

         UserModel(name: "Крендель",
                   avatar: "https://cdn.idntimes.com/content-images/post/20190216/labusas-org-ec92f317eb8a7039d3180e11c13ba810_600x400.jpg",
                   description: "Варю борщи",
                   website: "https://ya.ru",
                   nfts: [NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "7",
                                                     id: "757"),
                                   id: "6786"),
                          NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "8",
                                                     id: "757"),
                                   id: "6786")
                   ],
                   rating: "13",
                   id: "1"),

         UserModel(name: "Varik",
                   avatar: "https://img.goodfon.ru/original/800x480/4/cf/chiornaia-zmeia-red-belly-black-iazyk.jpg",
                   description: "Люблю выпить",
                   website: "https://ya.ru",
                   nfts: [],
                   rating: "9",
                   id: "2"),

         UserModel(name: "Sharik",
                   avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                   description: "Дуремар",
                   website: "https://ya.ru",
                   nfts: [],
                   rating: "10",
                   id: "8"),

         UserModel(name: "Bobik",
                   avatar: "Битая ссылка",
                   description: "Быстроо езжу на машине",
                   website: "https://ya.ru",
                   nfts: [NFTModel(createdAt: "",
                                   name: "",
                                   images: [],
                                   rating: 2,
                                   description: "",
                                   price: 3,
                                   author: UserModel(name: "FGD",
                                                     avatar: "https://ya.ru",
                                                     description: "",
                                                     website: "https://ya.ru",
                                                     nfts: [],
                                                     rating: "11",
                                                     id: "757"),
                                   id: "6786")],
                   rating: "17",
                   id: "0"),

         UserModel(name: "Krokus",
                    avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                    description: "Очень хороший друг",
                    website: "https://ya.ru",
                    nfts: [NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "1",
                                                      id: "757"),
                                    id: "6786"),
                           NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "2",
                                                      id: "757"),
                                    id: "6786"),
                           NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "3",
                                                      id: "757"),
                                    id: "6786")
                    ],
                    rating: "17",
                    id: "1"),

          UserModel(name: "Pokus",
                    avatar: "https://img.goodfon.ru/original/800x480/4/cf/chiornaia-zmeia-red-belly-black-iazyk.jpg",
                    description: "Очень плохое существо",
                    website: "https://ya.ru",
                    nfts: [],
                    rating: "18",
                    id: "2"),

          UserModel(name: "Очень огромное имя Васисуалий Васисуальевич Изподвыпедвертов",
                    avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                    description: "Странный",
                    website: "https://ya.ru",
                    nfts: [],
                    rating: "19",
                    id: "4"),

          UserModel(name: "Shmolex",
                    avatar: "https://i.ytimg.com/vi/p2jXct3Ewbo/hqdefault.jpg",
                    description: "Очень дерзкий",
                    website: "https://ya.ru",
                    nfts: [],
                    rating: "Битый рейтинг",
                    id: "6"),

          UserModel(name: "Jonni",
                    avatar: "https://cdn.idntimes.com/content-images/post/20190216/labusas-org-ec92f317eb8a7039d3180e11c13ba810_600x400.jpg",
                    description: "Варю борщи",
                    website: "https://ya.ru",
                    nfts: [NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "7",
                                                      id: "757"),
                                    id: "6786"),
                           NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "8",
                                                      id: "757"),
                                    id: "6786")
                    ],
                    rating: "13",
                    id: "1"),

          UserModel(name: "Poni",
                    avatar: "https://img.goodfon.ru/original/800x480/4/cf/chiornaia-zmeia-red-belly-black-iazyk.jpg",
                    description: "Люблю выпить",
                    website: "https://ya.ru",
                    nfts: [],
                    rating: "20",
                    id: "2"),

          UserModel(name: "Sharik",
                    avatar: "https://img01.kupiprodai.ru/092016/1474549920694.jpg",
                    description: "Дуремар",
                    website: "https://ya.ru",
                    nfts: [],
                    rating: "32",
                    id: "8"),

          UserModel(name: "Sloun",
                    avatar: "Битая ссылка",
                    description: "Быстроо езжу на машине",
                    website: "https://ya.ru",
                    nfts: [NFTModel(createdAt: "",
                                    name: "",
                                    images: [],
                                    rating: 2,
                                    description: "",
                                    price: 3,
                                    author: UserModel(name: "FGD",
                                                      avatar: "https://ya.ru",
                                                      description: "",
                                                      website: "https://ya.ru",
                                                      nfts: [],
                                                      rating: "11",
                                                      id: "757"),
                                    id: "6786")],
                    rating: "33",
                    id: "0")
        ]

    }
}
